<div class="container principal">
  <h1>MANUAL</h1>
  <hr>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer tempor massa ullamcorper, auctor dolor vitae, vulputate nisl. Nulla facilisi. Vestibulum tristique interdum purus, eu varius ex. Quisque tempor, ipsum ac feugiat fermentum, ex libero feugiat metus, in facilisis augue tellus ac enim. Proin vestibulum commodo massa, ac mollis mauris suscipit eget. Cras sed tortor in lacus accumsan mollis at eget purus. Phasellus tempor vel lectus ac tempus. In posuere, turpis quis consectetur egestas, nunc urna porta ligula, eu viverra diam tortor nec dui. Pellentesque fringilla nec eros a vulputate. Aliquam erat volutpat. Aliquam non ante ex. Donec aliquam quam mauris, sed rutrum purus condimentum vehicula.<br><br>

Curabitur quis facilisis tortor. Etiam pharetra ex quam, non finibus nisl lacinia quis. Aliquam vel dui aliquam, volutpat nisi ut, fermentum dui. Etiam nec nibh purus. Nulla tellus nisl, elementum sit amet augue id, tempus congue quam. Aliquam id diam et sem rhoncus sollicitudin ut at nunc. Aliquam ut nunc in felis vulputate finibus vel viverra erat. Phasellus varius, nibh sed tincidunt fringilla, augue lacus molestie erat, pretium cursus lorem risus at erat. Cras faucibus tristique commodo.<br><br>

Sed interdum pharetra turpis, auctor egestas elit consectetur vel. Integer volutpat efficitur feugiat. Cras in justo in mi venenatis porttitor. Ut libero nulla, dignissim sed ultricies sed, tincidunt in mi. Nulla facilisi. Phasellus ut semper leo, a posuere eros. Fusce ut sapien erat. Mauris et mi sit amet sapien varius tincidunt ut sed est. Nullam vitae lectus in nibh venenatis ultrices. Sed molestie metus vel tempus sodales.<br><br>

Proin eget luctus urna. Aenean aliquet dolor quis dolor consequat, eu egestas augue egestas. Curabitur id tincidunt dolor. Suspendisse eu dolor erat. Aliquam eget lacus ut nisi facilisis venenatis. Proin facilisis mollis augue a convallis. Sed at sagittis neque. Aliquam porta justo vel metus pretium sollicitudin. Sed euismod, orci at maximus mattis, ex velit porta sapien, sed vestibulum dolor lectus et nisi. Donec nisi diam, consectetur in est in, feugiat gravida dui. Nullam ex nunc, ultricies sit amet efficitur ac, lacinia convallis arcu. Suspendisse nec diam id velit finibus euismod at at ligula.<br><br>
</div>